[package]
name = "helper-bins"
version = "0.1.0"
authors = ["Aaron Gallagher <_@habnab.it>"]
build = "build.rs"
publish = false

[features]

[dependencies]
capnp = "0.8"
capnp-rpc = "0.8"
clap = {version = "2.5.2", features = ["unstable"]}
futures = "*"
lazy_static = "0.2.1"
regex = "0.1.73"
sha1 = "0.1.1"
tempfile = "2.1.4"
tokio-core = "*"
tokio-process = "*"

# maybe later
# git2 = {version = "0.4.3", default-features = false}

[dependencies.tokio-more]
git = "https://github.com/tokio-rs/tokio-more"

[dependencies.tokio-service]
git = "https://github.com/tokio-rs/tokio-service"

[build-dependencies]
capnpc = "*"

[dev-dependencies]
fnconcat = "*"
