edition = "2021"
unstable_features = true

fn_args_layout = "Compressed"
group_imports = "StdExternalCrate"
imports_granularity = "Module"
match_block_trailing_comma = true
overflow_delimited_expr = true
trailing_comma = "Vertical"
use_try_shorthand = true
