on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    name: build hab-prompt-utils linux binaries
    steps:
      - uses: actions/checkout@v2.1.0

      - name: build on armv7+linux for armv6
        uses: uraimo/run-on-arch-action@v2.0.5
        with:
          arch: armv7
          distro: ubuntu18.04
          githubToken: ${{ github.token }}

          install: |
            apt-get update \
              && apt-get install -y curl \
              && rm -rf /var/lib/apt/lists/*
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
              | sh -s -- --default-host=arm-unknown-linux-gnueabihf

          run: |
            cd oh-my-zsh/helper-bins
            cargo build --release --target=arm-unknown-linux-gnueabihf

      - name: install rust
        uses: actions-rs/toolchain@v1

      - name: build for amd64
        uses: actions-rs/cargo@v1
        with:
          command: |
            cd oh-my-zsh/helper-bins
            cargo build --release
