on: [push]
# on:
#   push:
#     paths:
#       - 'oh-my-zsh/helper-bins/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: build hab-prompt-utils binaries

    # env:
    #   RUSTFLAGS: "-C linker=rust-lld"

    strategy:
      fail-fast: false
      matrix:
        target:
          - arm-unknown-linux-gnueabihf
          - x86_64-unknown-freebsd
          - x86_64-unknown-linux-musl
        include:
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v2.1.0

      - name: install tools
        run: sudo apt-get install -y build-essential capnproto musl-tools

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.target }}
          components: llvm-tools-preview

      - name: deal with rust cache
        uses: Swatinem/rust-cache@v1

      - name: cache cargo-cross
        uses: actions/cache@v2
        env:
          cache-name: cargo_cross
        with:
          path: ~/.cargo/bin/cargo-cross
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('~/.cargo/bin/cargo-cross') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: rust build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target }} --release --manifest-path oh-my-zsh/helper-bins/Cargo.toml

      - name: copy out
        run: |
          git status
