on: [push]
# on:
#   push:
#     paths:
#       - 'oh-my-zsh/helper-bins/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    name: build hab-prompt-utils linux binaries
    steps:
      - uses: actions/checkout@v2.1.0

      - name: build on armv7+linux for armv6
        uses: uraimo/run-on-arch-action@v2.0.5
        with:
          arch: armv7
          distro: ubuntu18.04
          githubToken: ${{ github.token }}

          install: |
            apt-get update \
              && apt-get install -y build-essential curl capnproto grep \
              && rm -rf /var/lib/apt/lists/*
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
              | sh -s -- -y --profile minimal --default-host=arm-unknown-linux-gnueabihf

          run: |
            source $HOME/.cargo/env
            cd oh-my-zsh/helper-bins
            cargo build --release --target=arm-unknown-linux-gnueabihf

  build-2:
    runs-on: ubuntu-18.04
    name: build hab-prompt-utils linux binaries (alt??)
    steps:
      - uses: actions/checkout@v2.1.0

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: install tools
        run: sudo apt-get install -y build-essential capnproto

      - name: build for amd64
        uses: actions-rs/cargo@v1
        with:
          command: |
            cd oh-my-zsh/helper-bins
            cargo build --release
