[package]
name = "helper-bins"
version = "0.1.0"
authors = ["Aaron Gallagher <_@habnab.it>"]

[dependencies]
clap = {version = "2.5.2", features = ["unstable"]}
sha1 = "0.1.1"
# maybe later
# git2 = {version = "0.4.3", default-features = false}

[dev-dependencies]
fnconcat = "*"
