on:
  push:
    branches:
      - gha-builder

jobs:
  build-linux:
    name: build on linux
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - arm-unknown-linux-gnueabihf
          - x86_64-unknown-freebsd
          - x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v4

      - name: set up rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: rust build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: "--locked --release --target=${{ matrix.target }}"

      - name: copy out
        uses: actions/upload-artifact@v4
        with:
          name: prompt-utils-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/hab-prompt-utils
          retention-days: 1

  build-macos:
    name: build on macos
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v4

      - name: set up rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: rust build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: "--locked --release --target=${{ matrix.target }}"

      - name: copy out
        uses: actions/upload-artifact@v4
        with:
          name: prompt-utils-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/hab-prompt-utils
          retention-days: 1

  commit:
    name: commit results
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: download the artifacts
        uses: actions/download-artifact@v4
        with:
          path: oh-my-zsh/helper-bins

      - name: copy in
        run: |
          cd oh-my-zsh/helper-bins
          mv ./prompt-utils-arm-unknown-linux-gnueabihf/hab-prompt-utils lfs-Linux-armv6l
          mv ./prompt-utils-x86_64-apple-darwin/hab-prompt-utils lfs-Darwin-x86_64
          mv ./prompt-utils-aarch64-apple-darwin/hab-prompt-utils lfs-Darwin-arm64
          mv ./prompt-utils-aarch64-unknown-linux-gnu/hab-prompt-utils lfs-Linux-aarch64
          mv ./prompt-utils-x86_64-unknown-freebsd/hab-prompt-utils lfs-FreeBSD-amd64
          mv ./prompt-utils-x86_64-unknown-linux-musl/hab-prompt-utils lfs-Linux-x86_64
          chmod +x */hab-prompt-utils

      - name: and commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto built binaries
