on:
  push:
    branches:
      - gha-builder

jobs:
  build-linux:
    name: build on linux
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            use-cross: true
          - target: arm-unknown-linux-gnueabihf
            use-cross: true
          - target: x86_64-unknown-freebsd
            use-cross: true
          - target: x86_64-unknown-linux-gnu
            use-cross: false

    steps:
      - uses: actions/checkout@v4

      - name: rust build
        uses: houseabsolute/actions-rust-cross@v1
        with:
          target: ${{ matrix.target }}
          force-use-cross: ${{ matrix.use-cross }}
          args: |
            --locked --release

      - name: copy out
        uses: actions/upload-artifact@v4
        with:
          name: prompt-utils-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/hab-prompt-utils
          retention-days: 1

  build-macos:
    name: build on macos
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v4

      - name: install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          components: ''

      - name: rust build
        run: |
          cargo build --locked --release --target=${{ matrix.target }}

      - name: copy out
        uses: actions/upload-artifact@v4
        with:
          name: prompt-utils-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/hab-prompt-utils
          retention-days: 1

  commit:
    name: commit results
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: download the artifacts
        uses: actions/download-artifact@v4
        with:
          path: oh-my-zsh/helper-bins

      - name: copy in
        run: |
          cd oh-my-zsh/helper-bins
          mv ./prompt-utils-arm-unknown-linux-gnueabihf/hab-prompt-utils lfs-Linux-armv6l
          mv ./prompt-utils-x86_64-apple-darwin/hab-prompt-utils lfs-Darwin-x86_64
          mv ./prompt-utils-aarch64-apple-darwin/hab-prompt-utils lfs-Darwin-arm64
          mv ./prompt-utils-aarch64-unknown-linux-gnu/hab-prompt-utils lfs-Linux-aarch64
          mv ./prompt-utils-x86_64-unknown-freebsd/hab-prompt-utils lfs-FreeBSD-amd64
          mv ./prompt-utils-x86_64-unknown-linux-gnu/hab-prompt-utils lfs-Linux-x86_64
          chmod +x */hab-prompt-utils

      - name: and commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto built binaries
